card_define("S000-C-096", function(card) 
    card:name("Character Card 096")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(4)
    card:attack(523)
end)
