card_define("S000-C-025", function(card) 
    card:name("Character Card 025")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(4)
    card:attack(538)
end)
