card_define("S000-C-074", function(card) 
    card:name("Character Card 074")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(4)
    card:attack(471)
end)
