card_define("S000-C-036", function(card) 
    card:name("Character Card 036")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(4)
    card:attack(512)
end)
