card_define("S000-C-052", function(card) 
    card:name("Character Card 052")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(5)
    card:attack(567)
end)
