card_define("S000-C-001", function(card) 
    card:name("Character Card 001")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(5)
    card:attack(616)
end)
