card_define("S000-C-062", function(card) 
    card:name("Character Card 062")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(6)
    card:attack(715)
end)
