card_define("S000-C-018", function(card) 
    card:name("Character Card 018")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(4)
    card:attack(520)
end)
