card_define("S000-C-030", function(card) 
    card:name("Character Card 030")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(1)
    card:attack(220)
end)
