card_define("S000-C-075", function(card) 
    card:name("Character Card 075")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(4)
    card:attack(459)
end)
