card_define("S000-C-097", function(card) 
    card:name("Character Card 097")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(5)
    card:attack(627)
end)
