card_define("S000-C-023", function(card) 
    card:name("Character Card 023")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(3)
    card:attack(419)
end)
