card_define("S000-C-061", function(card) 
    card:name("Character Card 061")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(5)
    card:attack(633)
end)
