card_define("S000-C-041", function(card) 
    card:name("Character Card 041")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(5)
    card:attack(588)
end)
