card_define("S000-C-086", function(card) 
    card:name("Character Card 086")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(4)
    card:attack(528)
end)
