card_define("S000-C-014", function(card) 
    card:name("Character Card 014")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(6)
    card:attack(718)
end)
