card_define("S000-C-079", function(card) 
    card:name("Character Card 079")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(2)
    card:attack(335)
end)
