card_define("S000-C-063", function(card) 
    card:name("Character Card 063")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(5)
    card:attack(643)
end)
