card_define("S000-C-085", function(card) 
    card:name("Character Card 085")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(3)
    card:attack(433)
end)
