card_define("S000-C-040", function(card) 
    card:name("Character Card 040")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(1)
    card:attack(204)
end)
