card_define("S000-C-059", function(card) 
    card:name("Character Card 059")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(0)
    card:attack(112)
end)
