card_define("S000-C-054", function(card) 
    card:name("Character Card 054")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(6)
    card:attack(727)
end)
