card_define("S000-C-046", function(card) 
    card:name("Character Card 046")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(4)
    card:attack(526)
end)
