card_define("S000-C-071", function(card) 
    card:name("Character Card 071")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(5)
    card:attack(638)
end)
