card_define("S000-C-031", function(card) 
    card:name("Character Card 031")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(5)
    card:attack(601)
end)
