card_define("S000-C-021", function(card) 
    card:name("Character Card 021")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(5)
    card:attack(623)
end)
