card_define("S000-C-015", function(card) 
    card:name("Character Card 015")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(2)
    card:attack(310)
end)
