card_define("S000-C-006", function(card) 
    card:name("Character Card 006")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(1)
    card:attack(222)
end)
