card_define("S000-C-088", function(card) 
    card:name("Character Card 088")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(5)
    card:attack(615)
end)
