card_define("S000-C-026", function(card) 
    card:name("Character Card 026")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(4)
    card:attack(514)
end)
