card_define("S000-C-035", function(card) 
    card:name("Character Card 035")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(2)
    card:attack(272)
end)
