card_define("S000-C-093", function(card) 
    card:name("Character Card 093")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(3)
    card:attack(374)
end)
