card_define("S000-C-067", function(card) 
    card:name("Character Card 067")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(3)
    card:attack(439)
end)
