card_define("S000-C-012", function(card) 
    card:name("Character Card 012")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(3)
    card:attack(431)
end)
