card_define("S000-C-048", function(card) 
    card:name("Character Card 048")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(5)
    card:attack(596)
end)
