card_define("S000-C-060", function(card) 
    card:name("Character Card 060")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(6)
    card:attack(699)
end)
