card_define("S000-C-008", function(card) 
    card:name("Character Card 008")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(1)
    card:attack(176)
end)
