card_define("S000-C-078", function(card) 
    card:name("Character Card 078")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(1)
    card:attack(226)
end)
