card_define("S000-C-076", function(card) 
    card:name("Character Card 076")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(4)
    card:attack(534)
end)
