card_define("S000-C-051", function(card) 
    card:name("Character Card 051")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(5)
    card:attack(568)
end)
