card_define("S000-C-011", function(card) 
    card:name("Character Card 011")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(0)
    card:attack(139)
end)
