card_define("S000-C-034", function(card) 
    card:name("Character Card 034")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(5)
    card:attack(576)
end)
