card_define("S000-C-077", function(card) 
    card:name("Character Card 077")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(6)
    card:attack(681)
end)
