card_define("S000-C-039", function(card) 
    card:name("Character Card 039")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(2)
    card:attack(312)
end)
