card_define("S000-C-095", function(card) 
    card:name("Character Card 095")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(0)
    card:attack(100)
end)
