card_define("S000-C-065", function(card) 
    card:name("Character Card 065")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(2)
    card:attack(252)
end)
