card_define("S000-C-045", function(card) 
    card:name("Character Card 045")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(2)
    card:attack(304)
end)
