card_define("S000-C-050", function(card) 
    card:name("Character Card 050")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(3)
    card:attack(444)
end)
