card_define("S000-C-047", function(card) 
    card:name("Character Card 047")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(6)
    card:attack(714)
end)
