card_define("S000-C-005", function(card) 
    card:name("Character Card 005")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(4)
    card:attack(497)
end)
