card_define("S000-C-072", function(card) 
    card:name("Character Card 072")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(2)
    card:attack(331)
end)
