card_define("S000-C-013", function(card) 
    card:name("Character Card 013")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(2)
    card:attack(264)
end)
