card_define("S000-C-002", function(card) 
    card:name("Character Card 002")
    card:card_type("character")
    card:attribute("rationality") 
    card:category("math")
    card:cost(0)
    card:attack(115)
end)
